title: Saša Nikolič
subtitle: Drupal / Web developer
description: >- # this means to ignore newlines until "baseurl:"
  This is my window to the open internet world.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Saša Nikolič
author_bio: Hi, my name is Saša (pronounced as "Sasha"). Happy coder, public speaker and dog lover.
author_email: "nikolic.sasa09@gmail.com"
author_location: Slovenia
author_website_url: "https://sasanikolic.com"
typewrite-text: I turn coffee into code, use tabs over spaces and \"never\" broke production.

# Experiences
author_work_experiences:
            - company_name: MD Systems
              company_logo: md-systems.svg
              company_url: https://md-systems.ch
              designation: Web Developer
              description: Web development with Drupal open source contribution
              visibility: true
            - company_name: Amazee Labs
              company_logo: amazeelabs.png
              company_url: https://www.amazeelabs.com/en
              designation: Web Developer
              description: Worked on various Decoupled Drupal Projects
              visibility: true
            - company_name: Google Code-in 2016
              company_logo: google.png
              company_url: https://codein.withgoogle.com/archive/
              designation: Mentor
              description: Mentoring students with their Drupal projects.
              visibility: true
            - company_name: Google Summer of Code 2016
              company_logo: google-summer-of-code.png
              company_url: https://groups.drupal.org/node/510665
              designation: Student developer  
              description: Development of CKEditor plugins for the Translation Management Module Tool for Drupal 8.
              visibility: true  
            - company_name: NGN Media
              company_logo: ngn.svg
              company_url: https://www.ngn.si
              designation: Web Developer
              description: Full stack web development with a custom CMS
              visibility: true
# Education
author_education_details:
              - college_logo: up-famnit.png
                college_name: UP FAMNIT
                college_url: https://www.famnit.upr.si/en
                college_degree: Master's Degree
                description: Master's Degree of Computer and Information Sciences
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: canyon.png
                project_title: Canyon bikes outlet scraper
                project_description: A Python web scraper built for scraping a page with outlet bikes. The app sends a email notification when the page changes.
                project_url: _enter_url_here_
                visibility: true
              - project_thumbnail: ckeditor-plugins.png
                project_title: TMGMT CKeditor plugins
                project_description: A Drupal module to segment the translation text as an extension of the TMGMT module. Built as my Google Summer of Code 2016 project.
                project_url: https://www.drupal.org/sandbox/sasanikolic/2737249
                visibility: true

# social links
twitter_username: sasanikolic90
github_username:  sasanikolic90
facebook_username: sasanikolic123
linkedin_username: saša-nikolič-62399992
# behance_username: johndoe
instagram_username: sasha.nklc
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sasanikolic90

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: nikolic.sasa09@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
